window.ATLAS_DATA = {
  campus: [
    {rank:1,name:'İzmir Yüksek Teknoloji Enstitüsü',meta:'Devlet · İzmir',score:527.1,grade:'A+',learning:90.1,campus:85.8,support:86.4,governance:89.2,resources:88.9,career:86.6,advantage:'Araştırma odaklı, güçlü öğrenme ve yerleşke deneyimi.',risk:'Alan yelpazesi kapsamlı üniversitelere göre daha dar.',confidence:'Yüksek'},
    {rank:2,name:'MEF Üniversitesi',meta:'Vakıf · İstanbul',score:512.8,grade:'A+',learning:89.4,campus:79.7,support:83.9,governance:91.4,resources:85.2,career:83.3,advantage:'Öğrenim deneyimi ve kurumsal yönetim puanı çok güçlü.',risk:'İstanbul yaşam maliyeti ve vakıf üniversitesi ücretleri.',confidence:'Yüksek'},
    {rank:3,name:'İhsan Doğramacı Bilkent Üniversitesi',meta:'Vakıf · Ankara',score:512.5,grade:'A+',learning:86.1,campus:83.2,support:83.4,governance:81.3,resources:91.9,career:86.6,advantage:'Öğrenme kaynaklarında listenin en güçlülerinden.',risk:'Burs dışı maliyet ve yoğun akademik tempo.',confidence:'Yüksek'},
    {rank:4,name:'İstanbul Teknik Üniversitesi',meta:'Devlet · İstanbul',score:506.4,grade:'A',learning:85.5,campus:85.3,support:83.1,governance:82.4,resources:87.8,career:82.2,advantage:'Köklü teknik ekosistem ve güçlü yerleşke deneyimi.',risk:'Kalabalık yapı ve İstanbul yaşam maliyeti.',confidence:'Yüksek'},
    {rank:5,name:'Abdullah Gül Üniversitesi',meta:'Devlet · Kayseri',score:506.1,grade:'A',learning:84.8,campus:81.9,support:81.4,governance:86.3,resources:86.2,career:85.5,advantage:'Dengeli memnuniyet profili ve İngilizce eğitim odağı.',risk:'Büyük şehirlerdeki kadar geniş işveren ağına erişim gerektirebilir.',confidence:'Yüksek'},
    {rank:6,name:'Özyeğin Üniversitesi',meta:'Vakıf · İstanbul',score:505.6,grade:'A',learning:85.1,campus:85.3,support:83.9,governance:83.7,resources:85.5,career:82.1,advantage:'Modern kampüs ve dengeli öğrenci deneyimi.',risk:'Burs dışı maliyet ve şehir merkezine mesafe.',confidence:'Yüksek'},
    {rank:7,name:'Sabancı Üniversitesi',meta:'Vakıf · İstanbul',score:500.0,grade:'A',learning:84.2,campus:80.7,support:85.1,governance:78.5,resources:85.4,career:86.1,advantage:'Program seçme esnekliği ve güçlü kariyer gelişimi.',risk:'Burs dışı maliyet ve şehir merkezine mesafe.',confidence:'Yüksek'},
    {rank:8,name:'Biruni Üniversitesi',meta:'Vakıf · İstanbul',score:491.0,grade:'A',learning:82.6,campus:82.1,support:79.1,governance:82.8,resources:84.8,career:79.7,advantage:'Sağlık bilimleri odaklı ekosistem ve dengeli kampüs deneyimi.',risk:'Alan çeşitliliği sağlık odağı dışında sınırlı olabilir.',confidence:'Yüksek'},
    {rank:9,name:'Gebze Teknik Üniversitesi',meta:'Devlet · Kocaeli',score:488.6,grade:'A',learning:76.5,campus:82.2,support:83.3,governance:79.8,resources:83.6,career:83.2,advantage:'Sanayi kümelerine yakın, teknik ve araştırma odağı güçlü.',risk:'Öğrenim deneyimi puanı ilk 10 içindeki bazı rakiplerinden düşük.',confidence:'Yüksek'},
    {rank:10,name:'Koç Üniversitesi',meta:'Vakıf · İstanbul',score:487.3,grade:'A',learning:83.3,campus:82.8,support:78.8,governance:69.7,resources:92.5,career:80.2,advantage:'Öğrenme kaynaklarında çok yüksek puan ve güçlü araştırma ağı.',risk:'Burs dışı maliyet; kurumsal yönetim memnuniyeti göreli düşük.',confidence:'Yüksek'}
  ],
  ea: [
    {rank:1,name:'Yönetim Bilişim Sistemleri',meta:'EA · Dijital iş × teknoloji',future:94,global:90,income:89,flex:96,eco:88,advantage:'İş, veri ve teknoloji arasında güçlü köprü; geniş rol havuzu.',risk:'Teknik derinlik için kodlama, veri ve ürün portföyü şart.',regulated:false,confidence:'Orta-yüksek'},
    {rank:2,name:'Ekonomi',meta:'EA · Analitik sosyal bilim',future:86,global:91,income:88,flex:94,eco:90,advantage:'Veri, politika, finans ve danışmanlığa açılan esnek temel.',risk:'Nicel araçlar ve İngilizce olmadan diploma tek başına ayrışmaz.',regulated:false,confidence:'Orta-yüksek'},
    {rank:4,name:'İşletme',meta:'EA · Yönetim ve strateji',future:82,global:90,income:88,flex:96,eco:91,advantage:'Sektörler arası en geniş rol ve yönetim geçişlerinden biri.',risk:'Yoğun mezun arzında staj, dil ve uzmanlıkla ayrışmak gerekir.',regulated:false,confidence:'Orta-yüksek'},
    {rank:3,name:'Ekonometri',meta:'EA · İstatistik × ekonomi',future:90,global:88,income:86,flex:91,eco:84,advantage:'Ekonomik düşünceyi veri bilimi ve tahminle birleştirir.',risk:'Program kalitesi ve yazılım eğitimi üniversiteler arasında değişir.',regulated:false,confidence:'Orta-yüksek'},
    {rank:5,name:'Finans / Bankacılık',meta:'EA · Sermaye ve risk',future:84,global:88,income:92,flex:85,eco:88,advantage:'Yüksek gelir tavanı; fintech, risk ve yatırım rolleri.',risk:'Döngüsel sektör; sertifikasyon ve güçlü nicel temel değerli.',regulated:false,confidence:'Orta'},
    {rank:6,name:'Uluslararası Ticaret ve Lojistik',meta:'EA · Küresel tedarik',future:88,global:89,income:82,flex:87,eco:84,advantage:'E-ticaret, tedarik zinciri ve operasyon dönüşümüyle büyüyen alan.',risk:'Operasyon temposu yüksek; yabancı dil kritik.',regulated:false,confidence:'Orta'},
    {rank:8,name:'Psikoloji',meta:'EA · İnsan ve davranış',future:84,global:65,income:78,flex:82,eco:86,advantage:'Davranış bilimi, UX araştırma, İK ve akademiye uzanabilir.',risk:'Klinik uygulama için lisansüstü eğitim ve ülkeye göre lisans gerekir.',regulated:true,confidence:'Orta'},
    {rank:10,name:'Hukuk',meta:'EA · Regülasyon ve muhakeme',future:77,global:50,income:86,flex:77,eco:89,advantage:'Regülasyon, teknoloji hukuku ve uyum alanlarında güçlü potansiyel.',risk:'Yargı sistemi ülkeye özgüdür; sınır ötesi taşınabilirlik sınırlı.',regulated:true,confidence:'Orta-yüksek'},
    {rank:7,name:'Siyaset Bilimi ve Uluslararası İlişkiler',meta:'EA · Politika ve diplomasi',future:76,global:82,income:73,flex:85,eco:84,advantage:'Kamu, STK, risk, araştırma ve kurumsal ilişkiler geçişleri.',risk:'Rekabet yüksek; dil, nicel yöntem ve uzmanlık gerekir.',regulated:false,confidence:'Orta'},
    {rank:9,name:'Sağlık Yönetimi',meta:'EA · Sağlık sistemi',future:86,global:67,income:76,flex:80,eco:82,advantage:'Yaşlanan nüfus ve sağlık hizmeti talebiyle istikrarlı alan.',risk:'Ülke mevzuatı ve kurum deneyimi taşınabilirliği sınırlar.',regulated:false,confidence:'Orta'}
  ],
  say: [
    {rank:1,name:'Bilgisayar / Yazılım Mühendisliği',meta:'SAY · AI, yazılım, siber',future:98,global:97,income:96,flex:97,eco:95,advantage:'AI, büyük veri, ağlar ve siber güvenlikle doğrudan hizalı.',risk:'Beceri yarı ömrü kısa; sürekli öğrenme ve gerçek ürün portföyü şart.',regulated:false,confidence:'Yüksek'},
    {rank:9,name:'Tıp',meta:'SAY · Sağlık ve yaşam',future:94,global:66,income:94,flex:78,eco:96,advantage:'Kalıcı toplumsal talep ve yüksek uzmanlaşma değeri.',risk:'Uzun eğitim; her ülkede denklik, dil ve lisans süreçleri.',regulated:true,confidence:'Yüksek'},
    {rank:3,name:'Elektrik-Elektronik Mühendisliği',meta:'SAY · Çip, enerji, haberleşme',future:94,global:95,income:92,flex:93,eco:94,advantage:'Enerji, yarı iletken, robotik ve haberleşmeye açılan çekirdek alan.',risk:'Güçlü matematik ve laboratuvar/proje deneyimi gerekir.',regulated:false,confidence:'Yüksek'},
    {rank:4,name:'Endüstri Mühendisliği',meta:'SAY · Optimizasyon ve operasyon',future:91,global:93,income:91,flex:97,eco:92,advantage:'Veri, operasyon, ürün, finans ve danışmanlığa esnek geçiş.',risk:'Teknik derinlik seçilen uzmanlığa göre sonradan inşa edilir.',regulated:false,confidence:'Yüksek'},
    {rank:2,name:'Matematik / İstatistik / Veri Bilimi',meta:'SAY · Modelleme ve veri',future:97,global:96,income:93,flex:95,eco:90,advantage:'AI ve karar biliminin temelini kuran sınır ötesi beceri seti.',risk:'Uygulama, kodlama ve sektör bilgisiyle tamamlanmazsa soyut kalabilir.',regulated:false,confidence:'Yüksek'},
    {rank:5,name:'Makine / Mekatronik Mühendisliği',meta:'SAY · Robotik ve üretim',future:91,global:94,income:88,flex:91,eco:93,advantage:'Robotik, otomasyon, mobilite ve ileri üretimde geniş saha.',risk:'Donanım rolleri coğrafya ve sanayi yatırımlarına daha bağımlı.',regulated:false,confidence:'Yüksek'},
    {rank:7,name:'Uçak-Uzay Mühendisliği',meta:'SAY · Havacılık ve uzay',future:90,global:88,income:93,flex:80,eco:89,advantage:'Yüksek teknoloji, savunma, uydu ve havacılıkta güçlü gelir tavanı.',risk:'İşveren havuzu dar; bazı roller vatandaşlık/güvenlik kısıtı taşır.',regulated:false,confidence:'Orta-yüksek'},
    {rank:6,name:'Kimya / Malzeme Mühendisliği',meta:'SAY · Batarya ve ileri malzeme',future:88,global:92,income:87,flex:86,eco:90,advantage:'Batarya, yarı iletken, enerji ve sürdürülebilir üretimin temelinde.',risk:'Rol yoğunluğu yazılıma göre daha düşük ve lokasyona bağlı.',regulated:false,confidence:'Orta-yüksek'},
    {rank:8,name:'Moleküler Biyoloji ve Genetik / Biyomühendislik',meta:'SAY · Biyoteknoloji',future:91,global:90,income:83,flex:81,eco:88,advantage:'Biyoteknoloji, tanı, ilaç ve hesaplamalı biyolojide büyüme alanı.',risk:'Ar-Ge rolleri için lisansüstü eğitim sıklıkla gerekli.',regulated:false,confidence:'Orta-yüksek'},
    {rank:10,name:'Diş Hekimliği',meta:'SAY · Klinik sağlık',future:84,global:57,income:91,flex:70,eco:90,advantage:'Uzmanlaşma ve özel klinik tarafında güçlü gelir potansiyeli.',risk:'Yüksek eğitim/ekipman maliyeti; yurt dışında denklik ve lisans.',regulated:true,confidence:'Yüksek'}
  ]
};
